<?php

/** @var \Padaviva\Chatbot\Block\Chatbot $block */
if($block->isEnabled()):
    
    
?>

<div id="padaviva-chat" data-mage-init='{"padaviva_chatbot": {"chatUrl": "<?php echo $block->getChatUrl();?>","historyUrl": "<?php echo $block->getHistoryUrl();?>"}}'>
    
    <div class="open-chat" data-role="open-chat">
        <i class=" fas fa-robot" data-role="open-chat"></i>
    </div>
    <div class="chat-popup" id="chat-popup">
        <form action="" class="chat-form-container">
            <div id="transcript-window-container">
                <div id="transcript-window">
                    
                </div>
                <div class="typing-indicator" style="display:none">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <input type="text" placeholder="Type message.." name="msg" id="chat-msg" required/>

            <button type="submit" class="btn" id="send-message">Send</button>
            <button type="button" class="btn cancel" data-role="close-chat">Close</button>
        </form>
    </div>
</div>


<?php endif;?>