<?php

/** @var \Padaviva\Chatbot\Block\Chatbot $block */
if($block->isEnabled()):
?>

<div id="padaviva-chat" data-mage-init='{"padaviva_chatbot": {"chatUrl": "HELLO WORLD!"}}'>
    <button class="open-button" data-role="open-chat">Chat</button>

    <div class="chat-popup" id="chat-popup">
        <form action="" class="chat-form-container">
            <label for="msg"><b>Message</b></label>
            <input type="text" placeholder="Type message.." name="msg" required/>

            <button type="submit" class="btn" id="send-message">Send</button>
            <button type="button" class="btn cancel" data-role="close-chat">Close</button>
        </form>
    </div>
</div>


<?php endif;?>